-- Crear tabla userPreferences
CREATE TABLE IF NOT EXISTS userPreferences (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL UNIQUE,
  theme ENUM('light', 'dark', 'system') NOT NULL DEFAULT 'dark',
  language VARCHAR(10) NOT NULL DEFAULT 'en',
  notificationsEnabled BOOLEAN NOT NULL DEFAULT TRUE,
  emailNotifications BOOLEAN NOT NULL DEFAULT TRUE,
  workflowNotifications BOOLEAN NOT NULL DEFAULT TRUE,
  leadNotifications BOOLEAN NOT NULL DEFAULT TRUE,
  ticketNotifications BOOLEAN NOT NULL DEFAULT TRUE,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
