/**
 * Communication Workflows - Automated workflows that include Ivy-Call
 * Coordinates multi-channel communication campaigns
 */

import { AgentType } from '../agents/core';

export interface WorkflowDefinition {
  id: string;
  name: string;
  description: string;
  department: string;
  steps: WorkflowStep[];
  triggers?: string[];
  estimatedDuration?: number; // in seconds
}

export interface WorkflowStep {
  id: string;
  name: string;
  agentType: AgentType;
  action: string;
  description: string;
  config: Record<string, any>;
  nextStep: string;
  onError: string;
}

/**
 * Workflow: Outbound Sales Call Campaign
 * Prospect → Call → Closer
 */
export const outboundSalesCallWorkflow: WorkflowDefinition = {
  id: 'outbound_sales_call',
  name: 'Outbound Sales Call Campaign',
  description: 'Automated workflow for outbound sales calls with follow-up',
  department: 'SALES',
  steps: [
    {
      id: 'step_1',
      name: 'Qualify Lead',
      agentType: AgentType.PROSPECT,
      action: 'qualify_lead',
      description: 'Ivy-Prospect qualifies the lead and determines if they are ready for a call',
      config: {
        minScore: 70,
        criteria: ['budget', 'authority', 'need', 'timeline']
      },
      nextStep: 'step_2',
      onError: 'end'
    },
    {
      id: 'step_2',
      name: 'Make Initial Call',
      agentType: AgentType.CALL,
      action: 'make_call',
      description: 'Ivy-Call makes the initial outbound call with personalized script',
      config: {
        maxAttempts: 3,
        retryDelay: 3600, // 1 hour
        script: 'generated' // Will be generated by AI based on lead context
      },
      nextStep: 'step_3',
      onError: 'step_4' // If call fails, send SMS
    },
    {
      id: 'step_3',
      name: 'Analyze Call Outcome',
      agentType: AgentType.CALL,
      action: 'analyze_sentiment',
      description: 'Analyze call sentiment and outcome',
      config: {
        positiveThreshold: 0.6
      },
      nextStep: 'step_5', // If positive, hand off to Closer
      onError: 'step_4' // If negative, send follow-up SMS
    },
    {
      id: 'step_4',
      name: 'Send Follow-up SMS',
      agentType: AgentType.CALL,
      action: 'send_sms',
      description: 'Send personalized follow-up SMS if call was unsuccessful',
      config: {
        message: 'generated',
        includeCalendarLink: true
      },
      nextStep: 'end',
      onError: 'end'
    },
    {
      id: 'step_5',
      name: 'Hand Off to Closer',
      agentType: AgentType.CLOSER,
      action: 'schedule_meeting',
      description: 'Ivy-Closer schedules a demo meeting with the qualified lead',
      config: {
        meetingDuration: 30,
        priority: 'high'
      },
      nextStep: 'end',
      onError: 'end'
    }
  ],
  triggers: ['manual', 'scheduled', 'lead_qualified'],
  estimatedDuration: 300 // 5 minutes
};

/**
 * Workflow: SMS Drip Campaign
 * Automated SMS nurture sequence
 */
export const smsDripCampaignWorkflow: WorkflowDefinition = {
  id: 'sms_drip_campaign',
  name: 'SMS Drip Campaign',
  description: 'Automated SMS nurture sequence over 7 days',
  department: 'SALES',
  steps: [
    {
      id: 'step_1',
      name: 'Send Welcome SMS',
      agentType: AgentType.CALL,
      action: 'send_sms',
      description: 'Send initial welcome message',
      config: {
        message: 'Hola {firstName}, gracias por tu interés en Ivy.AI. ¿Cuándo podemos agendar una demo?',
        delay: 0
      },
      nextStep: 'step_2',
      onError: 'end'
    },
    {
      id: 'step_2',
      name: 'Wait 2 Days',
      agentType: AgentType.CALL,
      action: 'wait',
      description: 'Wait for 2 days before next message',
      config: {
        duration: 172800 // 2 days in seconds
      },
      nextStep: 'step_3',
      onError: 'end'
    },
    {
      id: 'step_3',
      name: 'Send Value Proposition SMS',
      agentType: AgentType.CALL,
      action: 'send_sms',
      description: 'Send message highlighting key benefits',
      config: {
        message: 'generated', // AI-generated based on lead industry
        includeLink: true
      },
      nextStep: 'step_4',
      onError: 'end'
    },
    {
      id: 'step_4',
      name: 'Wait 3 Days',
      agentType: AgentType.CALL,
      action: 'wait',
      description: 'Wait for 3 days before final message',
      config: {
        duration: 259200 // 3 days
      },
      nextStep: 'step_5',
      onError: 'end'
    },
    {
      id: 'step_5',
      name: 'Send Final Call-to-Action SMS',
      agentType: AgentType.CALL,
      action: 'send_sms',
      description: 'Send final CTA with urgency',
      config: {
        message: 'generated',
        includeCalendarLink: true,
        urgency: 'high'
      },
      nextStep: 'step_6',
      onError: 'end'
    },
    {
      id: 'step_6',
      name: 'Check Response',
      agentType: AgentType.CALL,
      action: 'check_engagement',
      description: 'Check if lead responded to any SMS',
      config: {
        checkPeriod: 604800 // 7 days
      },
      nextStep: 'step_7', // If engaged, make call
      onError: 'end' // If not engaged, end workflow
    },
    {
      id: 'step_7',
      name: 'Make Follow-up Call',
      agentType: AgentType.CALL,
      action: 'make_call',
      description: 'Call engaged leads',
      config: {
        script: 'generated'
      },
      nextStep: 'end',
      onError: 'end'
    }
  ],
  triggers: ['manual', 'lead_created'],
  estimatedDuration: 604800 // 7 days
};

/**
 * Workflow: WhatsApp Engagement Campaign
 * Multi-touch WhatsApp campaign with rich media
 */
export const whatsappEngagementWorkflow: WorkflowDefinition = {
  id: 'whatsapp_engagement',
  name: 'WhatsApp Engagement Campaign',
  description: 'Automated WhatsApp campaign with images and interactive messages',
  department: 'SALES',
  steps: [
    {
      id: 'step_1',
      name: 'Send Welcome Message with Image',
      agentType: AgentType.CALL,
      action: 'send_whatsapp',
      description: 'Send welcome message with company logo',
      config: {
        messageType: 'image',
        imageUrl: 'https://ivy.ai/logo.png',
        caption: 'generated'
      },
      nextStep: 'step_2',
      onError: 'end'
    },
    {
      id: 'step_2',
      name: 'Wait for Response',
      agentType: AgentType.CALL,
      action: 'wait_for_response',
      description: 'Wait up to 24 hours for user response',
      config: {
        timeout: 86400 // 24 hours
      },
      nextStep: 'step_3', // If response, continue conversation
      onError: 'step_4' // If no response, send reminder
    },
    {
      id: 'step_3',
      name: 'AI-Powered Conversation',
      agentType: AgentType.CALL,
      action: 'ai_conversation',
      description: 'Engage in AI-powered conversation to qualify lead',
      config: {
        maxTurns: 10,
        qualificationGoal: true
      },
      nextStep: 'step_5',
      onError: 'end'
    },
    {
      id: 'step_4',
      name: 'Send Reminder Message',
      agentType: AgentType.CALL,
      action: 'send_whatsapp',
      description: 'Send gentle reminder if no response',
      config: {
        message: 'generated',
        includeButtons: true
      },
      nextStep: 'end',
      onError: 'end'
    },
    {
      id: 'step_5',
      name: 'Send Product Demo Video',
      agentType: AgentType.CALL,
      action: 'send_whatsapp',
      description: 'Send product demo video to qualified leads',
      config: {
        messageType: 'video',
        videoUrl: 'https://ivy.ai/demo.mp4',
        caption: 'Mira cómo Ivy.AI puede transformar tu negocio'
      },
      nextStep: 'step_6',
      onError: 'end'
    },
    {
      id: 'step_6',
      name: 'Schedule Demo Call',
      agentType: AgentType.CLOSER,
      action: 'schedule_meeting',
      description: 'Schedule live demo with Ivy-Closer',
      config: {
        sendCalendarInvite: true,
        viaWhatsApp: true
      },
      nextStep: 'end',
      onError: 'end'
    }
  ],
  triggers: ['manual', 'lead_qualified', 'website_chat'],
  estimatedDuration: 172800 // 2 days
};

/**
 * Workflow: Abandoned Cart Recovery (E-commerce)
 * Call + SMS + WhatsApp multi-channel recovery
 */
export const abandonedCartRecoveryWorkflow: WorkflowDefinition = {
  id: 'abandoned_cart_recovery',
  name: 'Abandoned Cart Recovery',
  description: 'Multi-channel campaign to recover abandoned carts',
  department: 'SALES',
  steps: [
    {
      id: 'step_1',
      name: 'Send SMS Reminder',
      agentType: AgentType.CALL,
      action: 'send_sms',
      description: 'Send immediate SMS reminder with discount code',
      config: {
        message: 'Hola {firstName}, dejaste {itemCount} productos en tu carrito. Usa el código SAVE10 para 10% de descuento.',
        includeLink: true,
        delay: 3600 // 1 hour after abandonment
      },
      nextStep: 'step_2',
      onError: 'step_3'
    },
    {
      id: 'step_2',
      name: 'Wait 6 Hours',
      agentType: AgentType.CALL,
      action: 'wait',
      description: 'Wait to see if SMS converts',
      config: {
        duration: 21600 // 6 hours
      },
      nextStep: 'step_3',
      onError: 'end'
    },
    {
      id: 'step_3',
      name: 'Check Cart Status',
      agentType: AgentType.CALL,
      action: 'check_cart_status',
      description: 'Check if cart was completed',
      config: {},
      nextStep: 'step_4', // If still abandoned, continue
      onError: 'end' // If completed, end workflow
    },
    {
      id: 'step_4',
      name: 'Send WhatsApp with Product Images',
      agentType: AgentType.CALL,
      action: 'send_whatsapp',
      description: 'Send WhatsApp with product images and 15% discount',
      config: {
        messageType: 'image',
        imageUrl: 'generated', // Product images from cart
        caption: '¡No te lo pierdas! 15% de descuento en tu carrito. Código: SAVE15',
        includeButtons: true
      },
      nextStep: 'step_5',
      onError: 'step_6'
    },
    {
      id: 'step_5',
      name: 'Wait 18 Hours',
      agentType: AgentType.CALL,
      action: 'wait',
      description: 'Wait to see if WhatsApp converts',
      config: {
        duration: 64800 // 18 hours
      },
      nextStep: 'step_6',
      onError: 'end'
    },
    {
      id: 'step_6',
      name: 'Make Personal Call',
      agentType: AgentType.CALL,
      action: 'make_call',
      description: 'Make personal call for high-value carts (>$500)',
      config: {
        minCartValue: 500,
        script: 'generated',
        offerDiscount: 20
      },
      nextStep: 'end',
      onError: 'end'
    }
  ],
  triggers: ['cart_abandoned'],
  estimatedDuration: 86400 // 24 hours
};

/**
 * Workflow: Customer Support Follow-up
 * Solve → Call → Feedback
 */
export const supportFollowupWorkflow: WorkflowDefinition = {
  id: 'support_followup',
  name: 'Customer Support Follow-up',
  description: 'Automated follow-up after ticket resolution',
  department: 'SUPPORT',
  steps: [
    {
      id: 'step_1',
      name: 'Wait After Resolution',
      agentType: AgentType.CALL,
      action: 'wait',
      description: 'Wait 24 hours after ticket resolution',
      config: {
        duration: 86400 // 24 hours
      },
      nextStep: 'step_2',
      onError: 'end'
    },
    {
      id: 'step_2',
      name: 'Send SMS Survey',
      agentType: AgentType.CALL,
      action: 'send_sms',
      description: 'Send satisfaction survey via SMS',
      config: {
        message: 'Hola {firstName}, ¿cómo calificarías la resolución de tu ticket? Responde del 1 al 5.',
        expectResponse: true
      },
      nextStep: 'step_3',
      onError: 'step_4'
    },
    {
      id: 'step_3',
      name: 'Analyze Response',
      agentType: AgentType.CALL,
      action: 'analyze_sentiment',
      description: 'Analyze satisfaction score',
      config: {
        lowScoreThreshold: 3
      },
      nextStep: 'step_5', // If low score, escalate
      onError: 'end' // If high score, end
    },
    {
      id: 'step_4',
      name: 'Send WhatsApp Survey',
      agentType: AgentType.CALL,
      action: 'send_whatsapp',
      description: 'Send survey via WhatsApp if SMS failed',
      config: {
        message: 'generated',
        includeButtons: true,
        buttons: ['😊 Excelente', '😐 Regular', '😞 Malo']
      },
      nextStep: 'step_3',
      onError: 'end'
    },
    {
      id: 'step_5',
      name: 'Make Follow-up Call',
      agentType: AgentType.CALL,
      action: 'make_call',
      description: 'Call customers with low satisfaction scores',
      config: {
        script: 'Lamentamos que tu experiencia no haya sido óptima. ¿Cómo podemos mejorar?',
        recordCall: true
      },
      nextStep: 'step_6',
      onError: 'end'
    },
    {
      id: 'step_6',
      name: 'Create Escalation Ticket',
      agentType: AgentType.SOLVE,
      action: 'create_ticket',
      description: 'Create escalation ticket for unresolved issues',
      config: {
        priority: 'high',
        assignTo: 'manager'
      },
      nextStep: 'end',
      onError: 'end'
    }
  ],
  triggers: ['ticket_resolved'],
  estimatedDuration: 172800 // 2 days
};

/**
 * Export all communication workflows
 */
export const communicationWorkflows: WorkflowDefinition[] = [
  outboundSalesCallWorkflow,
  smsDripCampaignWorkflow,
  whatsappEngagementWorkflow,
  abandonedCartRecoveryWorkflow,
  supportFollowupWorkflow
];
