import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Upload, Download, Target, Mail, Phone, Share2, Loader2, FileText } from "lucide-react";
import { toast } from "sonner";

export function CampaignsTab() {
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [campaignType, setCampaignType] = useState<"email" | "phone" | "social_media" | "multi_channel">("email");
  const [targetAudience, setTargetAudience] = useState("");
  const [socialPlatform, setSocialPlatform] = useState("");

  const { data: files, refetch: refetchFiles } = trpc.campaigns.getFiles.useQuery();
  const { data: leads } = trpc.campaigns.getLeads.useQuery();
  const { data: campaigns, refetch: refetchCampaigns } = trpc.campaigns.getCampaigns.useQuery();

  const uploadMutation = trpc.campaigns.uploadFile.useMutation({
    onSuccess: () => {
      toast.success("File uploaded successfully!");
      refetchFiles();
      setSelectedFile(null);
    },
    onError: (error) => {
      toast.error(`Upload failed: ${error.message}`);
    },
  });

  const parseMutation = trpc.campaigns.parseFile.useMutation({
    onSuccess: (data) => {
      toast.success(`Extracted ${data.leadsCount} leads from file!`);
      refetchFiles();
    },
  });

  const generateMutation = trpc.campaigns.generateCampaign.useMutation({
    onSuccess: () => {
      toast.success("Campaign generated by ROPA!");
      refetchCampaigns();
      setTargetAudience("");
      setSocialPlatform("");
    },
  });

  const updateStatusMutation = trpc.campaigns.updateCampaignStatus.useMutation({
    onSuccess: () => {
      toast.success("Campaign status updated!");
      refetchCampaigns();
    },
  });

  const handleFileUpload = async () => {
    if (!selectedFile) return;

    const reader = new FileReader();
    reader.onload = async (e) => {
      const base64 = e.target?.result?.toString().split(",")[1];
      if (!base64) return;

      uploadMutation.mutate({
        fileName: selectedFile.name,
        fileType: selectedFile.type,
        fileSize: selectedFile.size,
        fileData: base64,
      });
    };
    reader.readAsDataURL(selectedFile);
  };

  const handleGenerateCampaign = () => {
    if (!targetAudience) {
      toast.error("Please enter target audience");
      return;
    }

    generateMutation.mutate({
      type: campaignType,
      targetAudience,
      socialPlatform: campaignType === "social_media" ? socialPlatform : undefined,
    });
  };

  const getCampaignIcon = (type: string) => {
    switch (type) {
      case "email":
        return <Mail className="w-4 h-4" />;
      case "phone":
        return <Phone className="w-4 h-4" />;
      case "social_media":
        return <Share2 className="w-4 h-4" />;
      default:
        return <Target className="w-4 h-4" />;
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case "active":
        return "bg-green-500";
      case "draft":
        return "bg-yellow-500";
      case "paused":
        return "bg-orange-500";
      case "completed":
        return "bg-blue-500";
      default:
        return "bg-gray-500";
    }
  };

  return (
    <div className="space-y-6">
      {/* File Upload Section */}
      <Card className="bg-slate-900 border-slate-800">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Upload className="w-5 h-5 text-cyan-400" />
            Upload Client Data
          </CardTitle>
          <CardDescription>Upload Excel, PDF, or images with potential client information</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex gap-4">
            <Input
              type="file"
              accept=".xlsx,.xls,.csv,.pdf,.png,.jpg,.jpeg"
              onChange={(e) => setSelectedFile(e.target.files?.[0] || null)}
              className="bg-slate-950 border-slate-700"
            />
            <Button
              onClick={handleFileUpload}
              disabled={!selectedFile || uploadMutation.isPending}
              className="bg-cyan-600 hover:bg-cyan-700"
            >
              {uploadMutation.isPending ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Uploading...
                </>
              ) : (
                <>
                  <Upload className="w-4 h-4 mr-2" />
                  Upload
                </>
              )}
            </Button>
          </div>

          {/* Uploaded Files */}
          {files && files.length > 0 && (
            <div className="space-y-2">
              <h4 className="text-sm font-medium text-slate-400">Uploaded Files</h4>
              {files.map((file) => (
                <div
                  key={file.id}
                  className="flex items-center justify-between p-3 bg-slate-950 rounded-lg"
                >
                  <div className="flex items-center gap-3">
                    <FileText className="w-4 h-4 text-cyan-400" />
                    <div>
                      <p className="text-sm font-medium">{file.fileName}</p>
                      <p className="text-xs text-slate-400">
                        {(file.fileSize / 1024).toFixed(2)} KB • {file.processedLeads} leads extracted
                      </p>
                    </div>
                  </div>
                  <div className="flex gap-2">
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => parseMutation.mutate({ fileId: file.id })}
                      disabled={parseMutation.isPending || (file.processedLeads ?? 0) > 0}
                      className="border-cyan-500/30 hover:bg-cyan-500/10"
                    >
                      {parseMutation.isPending ? "Processing..." : "Extract Leads"}
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => window.open(file.s3Url, "_blank")}
                      className="border-cyan-500/30 hover:bg-cyan-500/10"
                    >
                      <Download className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Generate Campaign Section */}
      <Card className="bg-slate-900 border-slate-800">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Target className="w-5 h-5 text-cyan-400" />
            Generate Campaign with ROPA
          </CardTitle>
          <CardDescription>Let ROPA create intelligent sales campaigns based on your leads</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>Campaign Type</Label>
              <Select value={campaignType} onValueChange={(v: any) => setCampaignType(v)}>
                <SelectTrigger className="bg-slate-950 border-slate-700">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="email">📧 Email Campaign</SelectItem>
                  <SelectItem value="phone">📞 Phone Campaign</SelectItem>
                  <SelectItem value="social_media">📱 Social Media</SelectItem>
                  <SelectItem value="multi_channel">🌐 Multi-Channel</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {campaignType === "social_media" && (
              <div className="space-y-2">
                <Label>Social Platform</Label>
                <Select value={socialPlatform} onValueChange={setSocialPlatform}>
                  <SelectTrigger className="bg-slate-950 border-slate-700">
                    <SelectValue placeholder="Select platform" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="LinkedIn">LinkedIn</SelectItem>
                    <SelectItem value="Instagram">Instagram</SelectItem>
                    <SelectItem value="Facebook">Facebook</SelectItem>
                    <SelectItem value="Twitter">Twitter/X</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            )}
          </div>

          <div className="space-y-2">
            <Label>Target Audience</Label>
            <Textarea
              placeholder="Describe your target audience (e.g., 'Tech startups in Latin America looking to automate sales')"
              value={targetAudience}
              onChange={(e) => setTargetAudience(e.target.value)}
              className="bg-slate-950 border-slate-700 min-h-[100px]"
            />
          </div>

          <div className="flex items-center justify-between">
            <p className="text-sm text-slate-400">
              {leads?.length || 0} leads available for targeting
            </p>
            <Button
              onClick={handleGenerateCampaign}
              disabled={generateMutation.isPending}
              className="bg-gradient-to-r from-cyan-500 to-teal-500 hover:from-cyan-600 hover:to-teal-600"
            >
              {generateMutation.isPending ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Target className="w-4 h-4 mr-2" />
                  Generate Campaign
                </>
              )}
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Active Campaigns */}
      <Card className="bg-slate-900 border-slate-800">
        <CardHeader>
          <CardTitle>Active Campaigns</CardTitle>
          <CardDescription>Campaigns generated and managed by ROPA</CardDescription>
        </CardHeader>
        <CardContent>
          {campaigns && campaigns.length > 0 ? (
            <div className="space-y-3">
              {campaigns.map((campaign) => (
                <div
                  key={campaign.id}
                  className="p-4 bg-slate-950 rounded-lg border border-slate-800 hover:border-cyan-500/30 transition-colors"
                >
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex items-center gap-3">
                      {getCampaignIcon(campaign.type)}
                      <div>
                        <h4 className="font-medium">{campaign.name}</h4>
                        <p className="text-xs text-slate-400">{campaign.targetAudience}</p>
                      </div>
                    </div>
                    <Badge className={getStatusColor(campaign.status)}>{campaign.status}</Badge>
                  </div>

                  <p className="text-sm text-slate-300 mb-3 line-clamp-2">{campaign.content}</p>

                  <div className="flex gap-2">
                    {campaign.status === "draft" && (
                      <Button
                        size="sm"
                        onClick={() =>
                          updateStatusMutation.mutate({ campaignId: campaign.id, status: "active" })
                        }
                        className="bg-green-600 hover:bg-green-700"
                      >
                        Activate
                      </Button>
                    )}
                    {campaign.status === "active" && (
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() =>
                          updateStatusMutation.mutate({ campaignId: campaign.id, status: "paused" })
                        }
                        className="border-orange-500/30"
                      >
                        Pause
                      </Button>
                    )}
                    <Button size="sm" variant="outline" className="border-cyan-500/30">
                      View Details
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-center text-slate-400 py-8">
              No campaigns yet. Upload client data and generate your first campaign!
            </p>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
